name: compile

on: [push, fork]

jobs:
  build_apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '17'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: sudo npm install androidjs
      - run: sudo npm install -g androidjs-builder
      - run: sudo find /usr/local/lib/node_modules/androidjs-builder -type f -exec sed -i -e "s/state.progress.start();//g" {} \;
      - run: sudo find /usr/local/lib/node_modules/androidjs-builder -type f -exec sed -i -e "s/progress.start();//g" {} \;
      - run: sudo find /usr/local/lib/node_modules/androidjs-builder -type f -exec sed -i -e "s/process.stdout.clearLine();//g" {} \;
      - run: sudo find /usr/local/lib/node_modules/androidjs-builder -type f -exec sed -i -e "s/process.stdout.cursorTo(0);//g" {} \;
      - run: androidjs build --release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: Android
          files: dist/ventilateur.apk
