name: compile

on: [push, fork]

jobs:
  build_apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '17'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install androidjs
      - run: npm install -g androidjs-builder
      
      - name: "not a TTY! dirty patch androidjs-builder"  
        run: | 
          find / -type d -name "androidjs-builder" 2>/dev/null
          ls /usr/local/lib/node_modules
          sudo find /usr/local/lib/node_modules/androidjs-builder -type f -exec sed -i -e "s/\sprogress.start();//g" {} \;
          androidjs build --release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: Android
          files: dist/ventilateur.apk
